#!/usr/bin/env bash

__execp="$(basename $0)"
__usage="
Usage: $__execp <...paths>

Description:
    Generates a C++ module map for use in Swift/C++ Interop projects.
    This operation recursively finds all header files in each provided
    path and adds them to a module map file at the root of each path..

    The default for <...paths> is the current directory, but multiple
    paths may be added if necessary.
"

function gen-map () {
    pushd $1
    echo "// Automatically generated by robertmsale/.scripts/gen-module-map.sh" > ./module.modulemap
    echo "module $(basename $1) {" >> ./module.modulemap
    for header in $(find . \( -name "*.h" -o -name "*.hpp" \)); do
        echo "    header \"${header:2}\"" >> ./module.modulemap
    done
    echo "    export *" >> ./module.modulemap
    echo "}" >> ./module.modulemap
}

if [ $# -eq 0 ]
then
    gen-map $PWD
else
    for arg in $@; do
        gen-map $arg
    done
fi
